-- CREAZIONE DELLE VOCI DI MENU

INSERT INTO `voci_menu` (`voce_id`, `etichetta`, `icona`, `tooltip`, `codice_padre`, `url`, `isVisibile`) VALUES
(1, 'Anagrafica', 'fas fa-users', '', 0, 'anagrafica', 1),
(2, 'Aggiungi utente', '', '', 1, 'creaUtente.php', 1),
(3, 'Lista utenti', '', '', 1, 'listaUtenti.php', 1),
(4, 'Gestione badge', '', '', 1, 'listaBadgeAccesso.php', 1),
(5, 'Gestione ruoli', '', '', 1, 'gestioneRuoli.php', 1),
(6, 'Veicoli', 'fas fa-ambulance', '', 0, 'veicoli', 1),
(7, 'Aggiungi veicolo', 'fas fa-ambulance', '', 6, 'aggiungiVeicolo.php', 1),
(8, 'Lista veicoli', 'fas fa-ambulance', '', 6, 'listaVeicoli.php', 1),
(9, 'Zaini', 'fas fa-suitcase-rolling', '', 0, 'zaini', 1),
(10, 'Aggiungi zaino', 'fas fa-suitcase-rolling', '', 9, 'aggiungiZaino.php', 1),
(11, 'Lista zaini', '', '', 9, 'listaZaini.php', 1),
(12, 'Sacche', 'fas fa-suitcase', '', 0, 'sacche', 1),
(13, 'Aggiungi sacca', 'fas fa-suitcase', '', 12, 'aggiungiSacca.php', 1),
(14, 'Lista sacche', 'fas fa-suitcase', '', 12, 'listaSacche.php', 1),
(15, 'Prodotti', 'fas fa-notes-medical', '', 0, 'prodotti', 1),
(16, 'Aggiungi prodotto', 'fas fa-notes-medical', '', 15, 'schedaProdotto.php', 1),
(17, 'Lista prodotti', 'fas fa-notes-medical', '', 15, 'listaProdotti.php', 1),
(18, 'Lista etichette', 'fas fa-notes-medical', '', 15, 'listaQrProdotti.php', 1),
(19, 'Checklist', 'fas fa-clipboard-list', '', 0, 'checklist', 1),
(20, 'Lista checklist', 'fas fa-clipboard-list', '', 19, 'listaCheckList.php', 1),
(21, 'Reintegri', 'fas fa-people-carry', '', 0, 'reintegri', 1),
(22, 'Lista reintegri', 'fas fa-people-carry', '', 21, 'listaReintegri.php', 1),
(23, 'Classifica', 'fas fa-people-carry', '', 21, 'classificaReintegri.php', 1),
(24, 'Notifiche', 'fas fa-bell', '', 0, 'notifiche', 1),
(25, 'Lista notifiche', 'fas fa-bell', '', 24, 'listaNotifiche.php', 1),
(26, 'Messaggi', 'fas fa-envelope', '', 0, 'messaggi', 1),
(27, 'Lista messaggi', 'fas fa-envelope', '', 26, 'listaMessaggi.php', 1),
(28, 'Supporto tecnico', 'fas fa-cogs', '', 0, 'supporto', 1),
(29, 'Crediti', 'fas fa-cogs', '', 28, 'crediti.php', 1),
(30, 'Documentazione', 'fas fa-cogs', '', 28, 'https://github.com/RiccardoRiggi/NewReintegrApp', 1),
(31, 'Homepage', '', '', 28, 'index.php', 0),
(32, 'Modifica Utente', '', '', 1, 'modificaUtente.php', 0),
(33, 'Stampa Badge Singolo', '', '', 1, 'stampaBadgeAccessoSingolo.php', 0),
(34, 'Stampa Badge Gruppo', '', '', 1, 'stampaBadgeAccessoDiGruppo.php', 0),
(35, 'Modifica Veicolo', '', '', 6, 'modificaVeicolo.php', 0),
(36, 'Modifica Zaino', '', '', 9, 'modificaZaino.php', 0),
(37, 'Modifica Sacca', '', '', 12, 'modificaSacca.php', 0),
(38, 'Stampa Etichetta', '', '', 15, 'stampaQrProdottiDiGruppo.php', 0),
(39, 'Scheda Checklist', '', '', 19, 'schedaCheckList.php', 0),
(40, 'Scheda Reintegro', '', '', 21, 'schedaReintegro.php', 0),
(41, 'Lista Prodotti Strategica', '', '', 15, 'listaStrategica.php', 0),
(42, 'Lista Sigilli', '', '', 15, 'listaSigilli.php', 0);